/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageUpload: typeof import('./src/components/ImageUpload.vue')['default']
    ImageUploader: typeof import('./src/components/ImageUploader.vue')['default']
    PanoramicAndAxialViewer: typeof import('./src/components/PanoramicAndAxialViewer.vue')['default']
    PatientInfoForm: typeof import('./src/components/PatientInfoForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StlViewerProject: typeof import('./src/components/stlViewerProject.vue')['default']
    ThreeDimViewer: typeof import('./src/components/ThreeDimViewer.vue')['default']
  }
}
